### ISSUE TITLE
UserError: (u"NimbusSanL-Regu: (<type 'exceptions.KeyError'>, KeyError('NimbusSanL-Regu',),

### ISSUE THREAD

**Issue by crsilveira** [danimaribeiro/PyTrustNFe#103]
Odoo-10 - Ubuntu - server 16.04 :  
 File "/opt/odoo/odoo/odoo/service/report.py", line 120, in _check_report
    raise UserError('%s: %s' % (exc.message, exc.traceback))
UserError: (u"NimbusSanL-Regu: (<type 'exceptions.KeyError'>, KeyError('NimbusSanL-Regu',), <traceback object at 0x7fd75d35a200>)", '')

Resolvi este erro instalando a font no ubuntu e adicionando no danfe.py : 
 from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont

pdfmetrics.registerFont(TTFont('NimbusSanL-Regu', 'NimbusSanL-Regu.ttf'))
pdfmetrics.registerFont(TTFont('NimbusSanL-Bold', 'NimbusSanL-Bold.ttf'))

**Comment by danimaribeiro** [comment]
https://github.com/danimaribeiro/PyTrustNFe/blob/master3/pytrustnfe/nfe/danfe.py#L80
