### ISSUE TITLE
charmap certificado

### ISSUE THREAD

**Issue by chapzin** [danimaribeiro/PyTrustNFe#104]
Quando estou mandando abrir o arquivo do certificado A1 está dando esse erro:

certificado = open('e:\\projetopython\\nfe\\certificado\\companny.pfx', 'r').read()
  File "C:\Anaconda3\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 98: character maps to <undefined>

**Comment by danimaribeiro** [comment]
'rb' - read binary
