### ISSUE TITLE
Funciona com certificado digital tipo A3?

### ISSUE THREAD

**Issue by zerutreck** [danimaribeiro/PyTrustNFe#106]
Bom dia,

Estou com grande dificuldade para emitir certificado digital tipo A3, essa lib suporta?

**Comment by danimaribeiro** [comment]
A lib não faz o carregamento do certificado, você deve passar o certificado para o método de envio.
Ou seja, você deve carregar o mesmo previamente e passar como parâmetro para o enviar nfe.
Certificados A1 e A3 são o mesmo tipo de certificado, então a lib vai funcionar sim.

**Comment by zerutreck** [comment]
Danimar obrigado pela resposta. Alguma dica de como carregar o A3 da leitora(computador) para uma aplicação web?

**Comment by danimaribeiro** [comment]
Aplicação web não tem acesso a dispositivos conectados, somente aplicativo desktop ou plugin para chrome/firefox.

**Comment by zerutreck** [comment]
Tenho que assinar na máquina e mandar assinado para o webapp?ou apenas mando o arquivo (certificado) para a aplicação online?

**Comment by danimaribeiro** [comment]
Manda assinado já.
