### ISSUE TITLE
Erro no cancelamento da NFe.

### ISSUE THREAD

**Issue by crsilveira** [danimaribeiro/PyTrustNFe#140]
File "parser.pxi", line 1823, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:106272)
ValueError: Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.

alterei a linha abaixo : 
docCancel = ET.fromstring(cancelamento)

para : 
parser = ET.XMLParser(encoding='utf-8')
docCancel = ET.fromstring(cancelamento.encode('utf-8'), parser=parser)

**Comment by danimaribeiro** [comment]
Acho que já foi corrigido.
