### ISSUE TITLE
NF 4.0 Paraná 

### ISSUE THREAD

**Issue by felipeelopes** [danimaribeiro/PyTrustNFe#166]
Boa Tarde, a nota fiscal eletrônica para o estado do Paraná é emitida normalmente, porém ao consultar o retorno o erro abaixo é apresentado.

Falha no schema XML org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 6; cvc-elt.1: Cannot find the declaration of element 'NFe'.

**Comment by felipeelopes** [comment]
**XML de envio:**
`<consReciNFe xmlns="http://www.portalfiscal.inf.br/nfe" versao="4.00">
<tpAmb>2</tpAmb>
<nRec>411110217302308</nRec>
</consReciNFe>`

**XML de retorno:**
`<env:Envelope xmlns:env='http://www.w3.org/2003/05/soap-envelope'><env:Body xmlns:env='http://www.w3.org/2003/05/soap-envelope'><nfeResultMsg xmlns='http://www.portalfiscal.inf.br/nfe/wsdl/NFeRetAutorizacao4'><retConsReciNFe versao='4.00' xmlns='http://www.portalfiscal.inf.br/nfe'><tpAmb>2</tpAmb><verAplic>PR-v4_2_7</verAplic><nRec>411110217302308</nRec><cStat>104</cStat><xMotivo>Lote processado</xMotivo><cUF>41</cUF><dhRecbto>2018-08-09T16:16:48-03:00</dhRecbto><protNFe versao='4.00'><infProt><tpAmb>2</tpAmb><verAplic>PR-v4_2_7</verAplic><chNFe>41180816707658000178550010000000731688026477</chNFe><dhRecbto>2018-08-09T16:16:44-03:00</dhRecbto><cStat>215</cStat><xMotivo>Falha no schema XML org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 6; cvc-elt.1: Cannot find the declaration of element &apos;NFe&apos;.</xMotivo></infProt></protNFe></retConsReciNFe></nfeResultMsg></env:Body></env:Envelope>`

**Comment by danimaribeiro** [comment]
Não tenho muito o que fazer, não tenho certificado do PR para testar.

**Comment by felipeelopes** [comment]
Acredito ter achado o problema. 

O XML é montado de forma correta (observe a tag <NFe>:
`<enviNFe
    xmlns="http://www.portalfiscal.inf.br/nfe" versao="4.00">
    <idLote>10</idLote>
    <indSinc>0</indSinc>
    <NFe xmlns="http://www.portalfiscal.inf.br/nfe">
        <infNFe versao="4.00" Id="NFe41180816707658000178550010000000741656564764">`

Na hora de enviar o XML o namespace da tag <NFe> é removido:
`<enviNFe
    xmlns="http://www.portalfiscal.inf.br/nfe"
    xmlns:ns0="http://www.portalfiscal.inf.br/nfe/wsdl/NFeAutorizacao4"
    xmlns:soap-env="http://www.w3.org/2003/05/soap-envelope" versao="4.00">
    <idLote>10</idLote>
    <indSinc>0</indSinc>
    <NFe>
        <infNFe versao="4.00" Id="NFe41180816707658000178550010000000741656564764">`

**Comment by felipeelopes** [comment]
Resolvi adicionando na função _send logo após `first_operation = next(iter(client.wsdl.port_types[port].operations))`

A seguinte ação:
`if kwargs['estado'] == '41':
        namespaceNFe = xml.find(".//{http://www.portalfiscal.inf.br/nfe}NFe")
        if namespaceNFe is not None:
            namespaceNFe.set('xmlns', 'http://www.portalfiscal.inf.br/nfe')`

Não sei se é a melhor solução, mas resolveu para mim.

**Comment by danimaribeiro** [comment]
Envia um PR
