### ISSUE TITLE
416 - Rejeição: Falha na descompactação da área de dados

### ISSUE THREAD

**Issue by crsilveira** [danimaribeiro/PyTrustNFe#170]
Estou recebendo a falha acima, de forma aleatória.
Alguém com este problema... alguma solução ?

Recebo este erro, se rodo o odoo em outra porta por exemplo, consigo enviar a mesma nota sem problema, ou o inverso..

**Comment by danimaribeiro** [comment]
Isto corrige o problema:
https://github.com/danimaribeiro/PyTrustNFe/commit/8c132a3bbb76c9bdcd600eb795dc2040e47ed8a7

**Comment by crsilveira** [comment]
Muito obrigado .
