### ISSUE TITLE
Funcionamento com certificado A3

### ISSUE THREAD

**Issue by OtnaelRochaSilva** [danimaribeiro/PyTrustNFe#178]
Ola Danimar,
Este projeto atende a ambientes onde esteja sendo utilizado o certificado A3?

Obrigado,

**Comment by danimaribeiro** [comment]
Apenas passe o certificado para a função de assinar:

https://docs.python.org/3/library/ssl.html#ssl.SSLContext.load_default_certs

**Comment by OtnaelRochaSilva** [comment]
Obrigado Danimar, e parabéns pelo projeto! :)
