### ISSUE TITLE
URL QRCode e Consulta NFC-e

### ISSUE THREAD

**Issue by rodriguesraphael** [danimaribeiro/PyTrustNFe#199]
@danimaribeiro sobre as urls de para a construção do QR-Code e Url de consulta da NFC-e, pela que vi alguns estados possuem Url's diferentes para cada um, mas vi apenas função e Url do QR-Code no arquivo de servidores.
Acabei de ver esta [linha](https://github.com/danimaribeiro/PyTrustNFe/blob/f01405affaf763f154ae0a09d08b340b7f65532a/pytrustnfe/Servidores.py#L19), é isso que esta implementando. Talvez eu esteja enganado, mas caso contrário eu poderia ajudar com isto.

**Comment by danimaribeiro** [comment]
Sim, pode ser ajustado.

def url_nfce(estado, ambiente):
