### ISSUE TITLE
Assinatura de XML

### ISSUE THREAD

**Issue by rodrigorodriguescosta** [danimaribeiro/PyTrustNFe#2]
Oi Danimar, tudo bem? vc me respondou em outro issue a respeito da assinatura digital, nada feito com o Python3, baixei seu projeto e fiz o teste e funcionou, usando o Python 2.7

No seu teste tem assim o exemplo do XML para assinar

    '<?xml version="1.0" encoding="UTF-8"?>' \
               '<!DOCTYPE Envelope [ ' \
               '     <!ATTLIST Data Id ID #IMPLIED>' \
               ']>' \
               '<Envelope xmlns="urn:envelope">'  \
               '   <Data Id="NFe43150602261542000143550010000000761792265342">' \
               '     Hello, World!' \
               '   </Data>' \
               '</Envelope>'

Eu tentei assinar mesmo uma NFe mas sempre retorna  `RuntimeError: Erro ao realizar a assinatura do arquivo; status: "0"`, você tem um exemplo da assinatura de um lote?

Faz tempo que estou tentando fazer isso funcionar, eu uso o Python3 mas como não funciona(até o momento não conseguir) vou usar no Python2 somente para a assinatura, no caso o seu script `assinatura.py`, só não estou conseguindo assinar o XML mesmo da NFe.

**Comment by danimaribeiro** [comment]
Talvez seja o problema aqui, ta fixo ainda o Id.
https://github.com/danimaribeiro/PyTrustNFe/blob/master/pytrustnfe/servicos/Assinatura.py#L50

Eu ainda não finalizei completamente essa biblioteca, mas acredito que só passando o Id corretamente deve funcionar.

**Comment by danimaribeiro** [comment]
To querendo fazer essa biblioteca utlizar o signxml que tem suporte a python3, só que to meio sem tempo. Se vc modificar alguma coisa manda um PR depois.

**Comment by bittecnologia** [comment]
Eu criei um projeto com o signxml mas não funcionou, já já em mando para o github, nem com Python2 nem com Python3, vou upar já com o virtualenv.

Eu já mudei a chave lá no código só para testar mas não funcionou.
 O XML que estou tentando enviar é

     XML_ASSINAR = '<?xml version="1.0" encoding="UTF-8"?>' \
               '<!DOCTYPE enviNFe [ ' \
               '     <!ATTLIST NFe Id ID #IMPLIED>' \
               ']>' \
               '<NFe><infNFe Id="NFe99999999999999999999999999999999999999999999" versao="2.00"><ide><cUF>42</cUF><cNF>89424836</cNF><natOp>5405-VENDA PROD/SERV  D.ESTADO</natOp><indPag>1</indPag><mod>55</mod><serie>1</serie><nNF>3</nNF><dEmi>2010-12-07</dEmi><dSaiEnt>2010-12-07</dSaiEnt><tpNF>1</tpNF><cMunFG>4216602</cMunFG><tpImp>1</tpImp><tpEmis>1</tpEmis><cDV>1</cDV><tpAmb>2</tpAmb><finNFe>1</finNFe><procEmi>0</procEmi><verProc>1</verProc></ide><emit><CNPJ>99999999999999</CNPJ><xNome>AAAAAAA AAAAAAAAA A AAAAAAAA LTDA ME.</xNome><xFant>AAAAAAA AAAAAAAAA A AAAAAAAA LTDA ME.</xFant><enderEmit><xLgr>RUA AAAAAA AAAAAAA</xLgr><nro>99</nro><xBairro>AAAAAAAAA</xBairro><cMun>4216602</cMun><xMun>AAA AAAA</xMun><UF>SC</UF><CEP>88117370</CEP><cPais>1058</cPais><xPais>BRASIL</xPais><fone>9999999999</fone></enderEmit><IE>999999999</IE><CRT>1</CRT></emit><dest><CNPJ>99999999999999</CNPJ><xNome>AAAAAAAA AAAAAA A AAAAAAA LTDA</xNome><enderDest><xLgr>RUA AAA AAAAA - AAAAAA 99</xLgr><nro>999</nro><xBairro>AAAAAA AAA AAAAAAA</xBairro><cMun>4202008</cMun><xMun>AAAAAAAAA AAAAAAAA</xMun><UF>SC</UF><CEP>88330000</CEP><cPais>1058</cPais><xPais>BRASIL</xPais><fone>999999999</fone></enderDest><IE>999999999</IE></dest><det nItem="1"><prod><cProd>201</cProd><cEAN/><xProd>AAAAAAA AA AAAAA AA AAAAAAAA AA AAAAA</xProd><NCM>99</NCM><CFOP>5933</CFOP><uCom>Un</uCom><qCom>1.0000</qCom><vUnCom>10.0000</vUnCom><vProd>10.00</vProd><cEANTrib/><uTrib>Un</uTrib><qTrib>1.0000</qTrib><vUnTrib>10.0000</vUnTrib><indTot>1</indTot></prod><imposto><ICMS><ICMSSN102><orig>0</orig><CSOSN>400</CSOSN></ICMSSN102></ICMS><PIS><PISNT><CST>07</CST></PISNT></PIS><COFINS><COFINSNT><CST>07</CST></COFINSNT></COFINS></imposto></det><total><ICMSTot><vBC>0.00</vBC><vICMS>0.00</vICMS><vBCST>0.00</vBCST><vST>0.00</vST><vProd>10.00</vProd><vFrete>0.00</vFrete><vSeg>0.00</vSeg><vDesc>0.00</vDesc><vII>0.00</vII><vIPI>0.00</vIPI><vPIS>0.00</vPIS><vCOFINS>0.00</vCOFINS><vOutro>0.00</vOutro><vNF>10.00</vNF></ICMSTot></total><transp><modFrete>1</modFrete></transp><cobr/><infAdic><infCpl>Docto emitido por ME ou EPP optante pelo Simples Nacional Nao gera direito a Credito Fiscal de ICMS e de ISS. SEM VALOR FISCAL</infCpl></infAdic></infNFe></NFe>'


O que está no seu código funciona mas da NFe mesmo não funcionou, eu não entendi esses parâmetros de DOCTYPE no XML.

**Comment by danimaribeiro** [comment]
O doctype serve para dizer qual o elemento que é o ID a ser utilizado na assinatura.
Tem outra forma de fazer sem isto, mas é um pouco mais complicado:
http://pyxmlsec.labs.libre-entreprise.org/index.php?section=examples

A tag Id é no elemento infNFe não NFe, talvez seja esse o problema.
<!ATTLIST NFe Id ID #IMPLIED>'

**Comment by bittecnologia** [comment]
Era isso mesmo, funcionou, agora vamos vou ver se deixo funcionando o `signxml`, ainda não conseguir, mas já criei um projetinho no github (https://github.com/bittecnologia/AssinaturaDigitalNFE) , dá um erro mesmo seguindo o tutorial lá, se eu conseguir te digo.

Uma curiosidade, esse seu projeto já está funcionando? vi que tu cria os layouts de forma dinâmica né?

**Comment by danimaribeiro** [comment]
Apesar de ter os testes ainda estou com um erro na geração dinâmica do xml, está invertendo a ordem de alguns elementos. 
O único que testei até agora foi a consulta de cadastro.

**Comment by bittecnologia** [comment]
Encontrei esse outro aqui https://pypi.python.org/pypi/dm.saml2/3.1.3 mas só python2, parece que só o signxml que teoricamente funciona com python3, no exemplo que fiz ele funcionou com o python2, python3 dá erro, de repente postando o erro para eles no github eles possam ajudar ou pelo menos dizer se funciona ou não no python3.

No momento vou usar o `assinatura.py ` no python2, passar os parâmetros e fazer ele escrever o arquivo XML, ai a applicação feita em Pyton3 pega o arquivo, é o jeito até o momento.

**Comment by danimaribeiro** [comment]
Acabei efetuando umas modificações no signxml aqui:
https://github.com/Trust-Code/signxml

Consegui fazer o xml passar no validador da NF-e em relação a assinatura digital. Acredito que dê para usar agora o signxml.

**Comment by rodrigorodriguescosta** [comment]
muito bom, nao testei ainda mas vou testar, funcionou mesmo?

**Comment by danimaribeiro** [comment]
Sim, porém depende de uma modificação no signxml que foi feita merge hoje, mais uns dias já deve estar no pip .

**Comment by rodrigorodriguescosta** [comment]
Olá, fui tentar assinar mas nao funcionou, vc teria um exemplo da funcao?

minha funcao está retornando o xml assinado mas o NS xmlns="http://www.w3.org/2000/09/xmldsig#" fica na tag da NFe, e deveria ficar em Signature, mudando manualmente o ns pro canto certo ai da assinatura inválida.

outra coisa, ele retorna o xml com um monte de namespaces, ja tentei remover pelo componente XML mas nao conseguir, removi usando replace acredito que isso pode implicar também na invalidação da nfe, enfim, vc teria essa funcao funcionando?

da uma olhada
https://github.com/rodrigorodriguescosta/AssinaturaDigitalNFE/blob/master/assinatura.py

**Comment by danimaribeiro** [comment]
https://github.com/danimaribeiro/PyTrustNFe/blob/master/pytrustnfe/nfe/assinatura.py#L17
