### ISSUE TITLE
Boleto de cobrança

### ISSUE THREAD

**Issue by diegocatalao** [danimaribeiro/PyTrustNFe#234]
Boa noite.
Alguém tem alguma informação de como eu faço para gerar o boleto da NF-e que eu recebi? Tem como fazer com essa lib?

**Comment by danimaribeiro** [comment]
Ela só emite NF-e, para boleto em python pode usar essa:

https://github.com/Trust-Code/python-boleto

**Comment by diegocatalao** [comment]
Mas eu consigo pegar os boletos gerados contra meu CNPJ ou pela chave da nota / nsu?

**Comment by danimaribeiro** [comment]
Isso aí se chama DDA e tu precisa contratar com o teu banco, dai eles disponibilizam um arquivo chamado CNAB que tu pode ler e gerar o boleto a partir dele.
