### ISSUE TITLE
Exemplo de consulta e emissão de NF paulistana

### ISSUE THREAD

**Issue by thiagoceano** [danimaribeiro/PyTrustNFe#241]
Olá a todos.

Tentei encontrar a documentação para utilização dos métodos do PyTrustNFe mas não achei algo que possa me ajudar. Alguém poderia por favor me mostrar um exemplo de como consultar ou como gerar uma nota fiscal paulistana?

Obrigado desde já e agradeço especialmente ao danimaribeiro pela disponibilização do código.

**Comment by danimaribeiro** [comment]
https://github.com/Trust-Code/odoo-brasil/blob/12.0/br_nfse_paulistana/models/invoice_eletronic.py

**Comment by thiagoceano** [comment]
Obrigado!
