### ISSUE TITLE
Assinatura Digital do RPS incorreta

### ISSUE THREAD

**Issue by thiagoceano** [danimaribeiro/PyTrustNFe#242]
Olá,

Estou tentando enviar uma RPS para a NFS-e Paulistana e como _received_xml_ eu tenho o seguinte erro:

**Assinatura Digital do RPS incorreta - String verificada (420389600000100000000000120190909TNN00000000000200000000000000000003093226813106000105)**

Segue minha RPS(Coloquei X para informações sensíveis):

rps = [
     {
         'assinatura': 'XXXXXXXX',
         'serie': '00001',
         'numero': '00001',
         'data_emissao': '2019-09-09',
         'data_envio': '2019-09-09',
         'codigo_atividade': '03093',
         'valor_servico': 20.00,
         'valor_deducao': '0.00',
         'valor_pis': '0.00',
         'valor_cofins': '0.00',
         'valor_csll': '0.00',
         'valor_inss': '0.00',
         'valor_ir': '0.00',
         'iss_retido': 0,       
         'prestador': {
             'inscricao_municipal': 'XXXXXXXX'
         },
         'tomador': {
             'tipo_cpfcnpj': 2,
             'cpf_cnpj': 'XXXXXXXXXXXX',
             'inscricao_municipal': 'XXXXXXXX',
             'razao_social': 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
             'tipo_logradouro': '1',
             'logradouro': 'XXXXXXXXXXXXXXXXXXXXXXXX',
             'numero': 100,
             'bairro': 'Bela Vista',
             'cidade': '3550308',  # Codigo da cidade, de acordo com o IBGE
             'uf': 'SP',
             'cep': 'XXXXXXXX',
         },
         'codigo_atividade': '03093',
         'aliquota_atividade': '5.00',
         'descricao': 'Venda de servico'
     }
 ]  

Procurei a formatação de geração da assinatura dentro do pacote PyTrustNFe mas não consegui achá-lo.

Se precisarem de mais alguma informação para me ajudar, estou à disposição. Obrigado.

**Comment by danimaribeiro** [comment]
https://github.com/Trust-Code/odoo-brasil/blob/12.0/br_nfse_paulistana/models/invoice_eletronic.py#L200

Olhe este exemplo.
