### ISSUE TITLE
Como inserir quebra de linha

### ISSUE THREAD

**Issue by thiagoceano** [danimaribeiro/PyTrustNFe#251]
Olá,

Como faço para inserir quebra de linha no campo descrição para envio da NF-e (estou enviando a NF paulistana)?

Se tento colocar `&#013;` a emissão retorna o erro:

**Rejeicao: Assinatura difere do calculado.**

Obrigado desde já.

**Comment by danimaribeiro** [comment]
Como está descrito no manual, você não pode usar quebra de linha.

**Comment by thiagoceano** [comment]
Ops. Obrigado Danimaribeiro.
