### ISSUE TITLE
SSL Error nfe.fazenda.mg.gov.br'

### ISSUE THREAD

**Issue by leandrocamposcardoso** [danimaribeiro/PyTrustNFe#294]
.Erro de SSL (Bad Handshake) no nfe.fazenda.mg.gov.br

requests.exceptions.SSLError: HTTPSConnectionPool(host='nfe.fazenda.mg.gov.br', port=443): Max retries exceeded with url: /nfe2/services/CadConsultaCadastro4?wsdl (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_read_bytes', 'sslv3 alert handshake failure')])")))

**Comment by danimaribeiro** [comment]
Você precisa de certificados válidos para testar.
