### ISSUE TITLE
apagando tags vazias do xml

### ISSUE THREAD

**Issue by gustavoxpg** [danimaribeiro/PyTrustNFe#3]
Opa Danimar, tudo certo?.

você percebeu que na hora de assinar do xml, o retorno da função esta apagando tags vazias do xml de entrada?
no meu caso está apagando a tag `<cEANTrib />` (NFe > det > prod > cEANTrib)

e quando vou validar o xml de retorno no [site da sefaz](https://www.sefaz.rs.gov.br/NFE/NFE-VAL.aspx)
aponta um erro por falta dessa tag.

segue abaixo o xml de exemplo que estou usando.

`<?xml version="1.0" encoding="utf-8"?>
<NFe xmlns="http://www.tests.inf.br/tests">
   <infNFe versao="3.10" Id="NFe">
      <ide>
         <cUF>35</cUF>
         <cNF>44633102</cNF>
         <natOp>Venda</natOp>
         <indPag>1</indPag>
         <mod>55</mod>
         <serie>15</serie>
         <nNF>27</nNF>
         <dhEmi>2014-12-30T09:44:02-02:00</dhEmi>
         <tpNF>1</tpNF>
         <idDest>1</idDest>
         <cMunFG>3550308</cMunFG>
         <tpImp>1</tpImp>
         <tpEmis>1</tpEmis>
         <cDV>4</cDV>
         <tpAmb>2</tpAmb>
         <finNFe>1</finNFe>
         <indFinal>0</indFinal>
         <indPres>9</indPres>
         <procEmi>0</procEmi>
         <verProc>NF-e</verProc>
      </ide>
      <emit>
         <CNPJ>00000000000000</CNPJ>
         <xNome>Razao Social Ltda</xNome>
         <xFant>Nome Fantasia</xFant>
         <enderEmit>
            <xLgr>Rua do Emitente</xLgr>
            <nro>140</nro>
            <xBairro>Bairro</xBairro>
            <cMun>3550308</cMun>
            <xMun>TESTES</xMun>
            <UF>UF</UF>
            <CEP>00000000</CEP>
            <fone>1112345678</fone>
         </enderEmit>
         <IE>1234567890</IE>
         <CRT>3</CRT>
      </emit>
      <dest>
         <CNPJ>00000000000000</CNPJ>
         <xNome>Razao Social Ltda</xNome>
         <enderDest>
            <xLgr>Rua Teste</xLgr>
            <nro>10</nro>
            <xBairro>Bairro</xBairro>
            <cMun>3550308</cMun>
            <xMun>TESTES</xMun>
            <UF>SP</UF>
            <CEP>00000000</CEP>
            <fone>1112340000</fone>
         </enderDest>
         <indIEDest>9</indIEDest>
         <IE>000000000000</IE>
         <email>emeio@servidor.com.br</email>
      </dest>
      <det nItem="1">
         <prod>
            <cProd>codigo do produto</cProd>
            <cEAN />
            <xProd>Descricao do produto</xProd>
            <NCM>0000000</NCM>
            <CFOP>1234</CFOP>
            <uCom>UN</uCom>
            <qCom>1.0000</qCom>
            <vUnCom>1.0000</vUnCom>
            <vProd>1.00</vProd>
            <cEANTrib />
            <uTrib>UN</uTrib>
            <qTrib>1.0000</qTrib>
            <vUnTrib>1.0000</vUnTrib>
            <indTot>1</indTot>
         </prod>
         <imposto>
            <ICMS>
               <ICMS00>
                  <orig>0</orig>
                  <CST>00</CST>
                  <modBC>3</modBC>
                  <vBC>1.00</vBC>
                  <pICMS>18.0000</pICMS>
                  <vICMS>0.18</vICMS>
               </ICMS00>
            </ICMS>
            <PIS>
               <PISAliq>
                  <CST>01</CST>
                  <vBC>1.00</vBC>
                  <pPIS>0.65</pPIS>
                  <vPIS>0.01</vPIS>
               </PISAliq>
            </PIS>
            <COFINS>
               <COFINSAliq>
                  <CST>01</CST>
                  <vBC>1.00</vBC>
                  <pCOFINS>3.0000</pCOFINS>
                  <vCOFINS>0.03</vCOFINS>
               </COFINSAliq>
            </COFINS>
         </imposto>
         <infAdProd>obs</infAdProd>
      </det>
      <total>
         <ICMSTot>
            <vBC>1.00</vBC>
            <vICMS>0.18</vICMS>
            <vICMSDeson>0.00</vICMSDeson>
            <vBCST>0.00</vBCST>
            <vST>0.00</vST>
            <vProd>1.00</vProd>
            <vFrete>0.00</vFrete>
            <vSeg>0.00</vSeg>
            <vDesc>0.00</vDesc>
            <vII>0.00</vII>
            <vIPI>0.10</vIPI>
            <vPIS>0.01</vPIS>
            <vCOFINS>0.03</vCOFINS>
            <vOutro>0.00</vOutro>
            <vNF>1.10</vNF>
         </ICMSTot>
      </total>
      <transp>
         <modFrete>0</modFrete>
      </transp>
   </infNFe>
</NFe>`

**Comment by danimaribeiro** [comment]
Sim, eu notei.
Seria bom se os desenvolvedores da NFe usassem um padrão (ou pode enviar tag vazia ou não - se decidam)

Ainda to em desenvolvimento dessa lib, se for mexer e quiser enviar PR ficou muito agradecido.

Aqui no render_xml vou ter que fazer um esquema para preservar certas tags vazias:
https://github.com/danimaribeiro/PyTrustNFe/blob/master/pytrustnfe/xml/__init__.py#L21

Ou uma segunda opção seria remover o código que limpa as tags vazias e deixar o controle do que vai ou não no xml para o template xml do jinja, dai lá pode ser usado {% if else %} para controlar quando mostrar ou não.

Mas acredito que a primeira opção seja mais prática, pois acho que é só a tag cEAN e cEANTrib que podem ir vazias.

**Comment by gustavoxpg** [comment]
já fiz a correção desse problema localmente. mas estou com outro problema ao validar o xml na sefaz.
o erro é esse:
297 - [Simulacao] Rejeicao: Assinatura difere do calculado

você já teve esse erro quando estava testando o retorno do seu xml ou sabe como resolver?
obs: também já verifiquei que meu xml não tem nenhum caracter especial.
