### ISSUE TITLE
Erro ao instalar as dependências

### ISSUE THREAD

**Issue by psnma** [danimaribeiro/PyTrustNFe#32]
Tentei instalar o PyTrustNFe, no entanto ocorreu um erro ao instalar o pacote `suds`

```
Collecting suds>=0.4 (from PyTrustNFe==0.1.26)
  Downloading suds-0.4.tar.gz (104kB)
    100% |████████████████████████████████| 112kB 2.2MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-build-k26zewb7/suds/setup.py", line 20, in <module>
        import suds
      File "/private/tmp/pip-build-k26zewb7/suds/suds/__init__.py", line 154, in <module>
        import client
    ImportError: No module named 'client'
```

Procurei no Google e vi que `suds` foi descontinuado, recomendando usar `suds-jurko`.
* Estou usando o sistema Mac OS.
* Ao usar `pip install pytrustnfe` está vindo a versão antiga.
* http://stackoverflow.com/questions/14973852/suds-install-error-no-module-named-client/14974075

**Comment by danimaribeiro** [comment]
O pytrustnfe depende do suds_requests que depende do suds.
A menos que você migre o suds_requests, terá que usar o suds.
