### ISSUE TITLE
Danfe

### ISSUE THREAD

**Issue by edsonitk** [danimaribeiro/PyTrustNFe#34]
Olá,
Estou estudando sua biblioteca e acabei escrevendo uma classe que gera DANFE em PDF usando reportlab. Teria interesse em incorpora-la ao projeto?

**Comment by danimaribeiro** [comment]
Manda um pdf ai de exemplo, tenho interesse sim.

**Comment by edsonitk** [comment]
Aqui ou no seu mail?

**Comment by danimaribeiro** [comment]
Anexa um print aqui mesmo

**Comment by edsonitk** [comment]
![image](https://cloud.githubusercontent.com/assets/25555558/22621813/54ec4f1a-eb13-11e6-9fe7-2dc82caceb38.png)

**Comment by edsonitk** [comment]
Se quiser mando no seu mail o pdf.

**Comment by danimaribeiro** [comment]
Manda o PR já :)

**Comment by edsonitk** [comment]
PR??

**Comment by danimaribeiro** [comment]
Pull Request do código

**Comment by edsonitk** [comment]
Apanhando um pouco...não uso o github

**Comment by danimaribeiro** [comment]
Ainda não conseguiu?

**Comment by edsonitk** [comment]
Ainda não...eu tento abrir o Pull request mas não consigo. Nunca usei o github...

**Comment by edsonitk** [comment]
Eu uso windows...rss...depois eu procuro uma alternativa. Ou se preferir te passo o fonte depois e vc incorpora.

**Comment by danimaribeiro** [comment]
Qualquer coisa me envia por email, dai faço o commit como se você fosse o autor.

**Comment by edsonitk** [comment]
Já foi...abs

**Comment by danimaribeiro** [comment]
@edsonitk Muito obrigado mais uma vez pela contribuição, fiz os últimos ajustes em relação ao código do produto e a descrição.
