### ISSUE TITLE
Erro Schema - Rejeicao: Assinatura difere do calculado

### ISSUE THREAD

**Issue by rodriguesraphael** [danimaribeiro/PyTrustNFe#38]
Estou tendo erro na hora de validar a NFCe.
Testei o esquema e retorna um erro no certificado, porém este erro também ocorre na NFe e ainda assim é validada.
A mensagem de rejeição é a seguinte:
Rejeicao: Assinatura difere do calculado
Pesquisando vi que poderia ser caracteres especiais ou a assinatura. Caracteres especiais não é pois passa na validação e só aponta realmente o erro mostrado abaixo.
Se puder ajudar fico grato, acredito que pra finalizar a emissão da NFCe resta apenas isto mesmo.

Schema XML: The 'http://www.w3.org/2000/09/xmldsig#:X509Certificate' element is invalid - The value 'MIIHyDCCBbCgAwIBAgIIKwEWBhY+g7QwDQYJKoZIhvcNAQELBQAwgYkxCzAJBgNV\nBAYTAkJSMRMwEQYDVQQKEwpJQ1AtQnJhc2lsMTQwMgYDVQQLEytBdXRvcmlkYWRl\nIENlcnRpZmljYWRvcmEgUmFpeiBCcmFzaWxlaXJhIHYyMRIwEAYDVQQLEwlBQyBT\nT0xVVEkxGzAZBgNVBAMTEkFDIFNPTFVUSSBNdWx0aXBsYTAeFw0xNjA2MjAxNzAz\nMzZaFw0xNzA2MTYxMzM2MDBaMIHXMQswCQYDVQQGEwJCUjETMBEGA1UEChMKSUNQ\nLUJyYXNpbDE0MDIGA1UECxMrQXV0b3JpZGFkZSBDZXJ0aWZpY2Fkb3JhIFJhaXog\nQnJhc2lsZWlyYSB2MjESMBAGA1UECxMJQUMgU09MVVRJMRswGQYDVQQLExJBQyBT\nT0xVVEkgTXVsdGlwbGExGjAYBgNVBAsTEUNlcnRpZmljYWRvIFBKIEExMTAwLgYD\nVQQDEydNLiBETyBTLiBNLiBCUkFOREFPIC0gTUU6MDc1Mzc5NzIwMDAxNjkwggEi\nMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCjInC9oyj7DzkipvSHB2SyrwJC\nEjVJYHu25A/1rkzD1O8B3lVyDFIbQHfcKrN/3w1u3epNqMu2j+DzRgFe8Kn4+dvi\nmk176D+Vo+Nt5ZO6Pu9R4g/71SyyF99Wq1oayy0bA6V/JcdiyqWaQ0m17S0tinvS\nBI+dGmcpSiHBfpMSBxCKPIJOJAwXN1SXrqFZ6rRxH+pRVHsD4uHN5XU6KXMHDq7Z\nswVnpj8HtPzUfVYxDMKSNtaW3y7QJcMngUv28Z4yNx0Z1LXhQPv4RiXKfyvFbbbQ\nMZNeLRJJMcxSSfJuZF2Xz15R+6s7CbROQHdL7o+vEyR13ysYcTKCLFJaFnEtAgMB\nAAGjggLiMIIC3jBUBggrBgEFBQcBAQR...' is invalid according to its datatype 'http://www.w3.org/2001/XMLSchema:base64Binary' - The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.
Caminho: enviNFe/NFe[1]/Signature/KeyInfo/X509Data/X509Certificate/

**Comment by danimaribeiro** [comment]
Hoje eu não vou ter tempo de ver isto, mas a principio NFe e NFCe é o mesmo tipo de assinatura, como está funcionando para a NFe não precisa modificar nada para a NFCe.

**Comment by rodriguesraphael** [comment]
Na assinatura está saindo \n indicando Enter.

Em qui, 9 de fev de 2017 07:06, Danimar Ribeiro <notifications@github.com>
escreveu:

**Comment by danimaribeiro** [comment]
Até faz sentido, mas estou emitindo nota diariamente em vários estados.
:thinking:

**Comment by rodriguesraphael** [comment]
É como eu disse, emito a NFe com os mesmos valores, removendo apenas as tags de NFCe (vpag, tpag, ...) E passa tranquilo. Porém vou pra NFCe e retorna esta mensagem.

**Comment by rodriguesraphael** [comment]
Pronto, deu certo.
Estava passando os dados do destinatário no XML e no QRcode esta informação é omitida.
Já deu certo Danimar.
