### ISSUE TITLE
Remoção do namespace ds: na assinatura

### ISSUE THREAD

**Issue by rodrigorodriguescosta** [danimaribeiro/PyTrustNFe#4]
Danimar, como vc me respondeu, realmente funcionou a assinatura com seu exemplo, porém, a assinatura é retornado com um namespace ds:, o validaor valida tudo, consigo enviar a nfe, eventos etc, porém, fui enviar o Manifesto do Destinatário para o WS ambiente nacional e o mesmo retorna dizendo que não aceita esse namespace 

como tirar esse `ds:` ? 

> Rejeição: 587-Rejeição: Usar somente o namespace padrão da NF-e ,

 se eu remover com um replace a assinatura fica inválida, veja como é gerado.

`<ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
            <ds:SignedInfo>
                <ds:CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>
                <ds:SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
                <ds:Reference URI="#NFe24161002902736000261550010000000061000000066">
                    <ds:Transforms>
                        <ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
                        <ds:Transform Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>
                    </ds:Transforms>
                    <ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
                    <ds:DigestValue>Q6broyQwxc2AaHmTb9iYXd9Q4/0=</ds:DigestValue>
                </ds:Reference>
            </ds:SignedInfo>
            <ds:SignatureValue>
                YI+nPpZjcTfskv1KELiFhYnAAwfEPyNzbETftpM21ndLPZG2abqP31hn2cC0Xt8sXCFdvXszBME3okUpxOdS0O8rQb+3PvRgfzx0LYtjA5WEw+Hdg9Emr8qrmQGbQGxCsPC1qb1GAx/DxWSIp/6tK9Bs51xExnhw9F6+gS7+EcpwER62V32E8TfdbaVQvmW13USvLtl9aGwePn0pE7xDYLrUAbLBwWdjZLzgWouy2hw3Q1e2TxValNvWC0fg2F+SLghzvwkxUSK2TJQyhCZ/wfZZ3PLw+HvPAUtL7DlnEgcWTozcQ+X7wJtnlNoTF6mmbWiJLm6hjvEptniDtNypXg==
            </ds:SignatureValue>
            <ds:KeyInfo>
                <ds:X509Data>
                    <ds:X509Certificate>MIIIADCCBeigAwIBAgIIey8fHVSRFEEwDQYJKoZIhvcNAQELBQAwdTELMAkGA1UE
                        BhMCQlIxEzARBgNVBAoTCklDUC1CcmFzaWwxNjA0BgNVBAsTLVNlY3JldGFyaWEg
                        ZGEgUmVjZWl0YSBGZWRlcmFsIGRvIEJyYXNpbCAtIFJGQjEZMBcGA1UEAxMQQUMg
                        U0VSQVNBIFJGQiB2MjAeFw0xNjAxMjYxOTU3MDBaFw0xNzAxMjUxOTU3MDBaMIHf
                        MQswCQYDVQQGEwJCUjELMAkGA1UECBMCUk4xDjAMBgNVBAcTBU5BVEFMMRMwEQYD
                        VQQKEwpJQ1AtQnJhc2lsMTYwNAYDVQQLEy1TZWNyZXRhcmlhIGRhIFJlY2VpdGEg
                        RmVkZXJhbCBkbyBCcmFzaWwgLSBSRkIxFjAUBgNVBAsTDVJGQiBlLUNOUEogQTEx
                        EDAOBgNVBAsTB0FSIENOREwxPDA6BgNVBAMTM0FMUEhBVEVDIFNFUlZJQ09TIEUg
                        Q09NRVJDSU8gTFREQSBNRTowMjkwMjczNjAwMDI2MTCCASIwDQYJKoZIhvcNAQEB
                        BQADggEPADCCAQoCggEBAJKJyifSzRMkJb6UsNEGS9BVB9w0DHnCKExVPpChk915
                        no9Usq0PcCDrhJGjwE/841V+bXXXQFzmK4hb+Zgr8+W3yLQ3RBeCAO6e7CL6Ayyc
                        hJGUu9x7yZ+RVe5SjYvOVCYEZjezDFPGF0OpzUu1NITZ6s9s9In3pDSI1kmwi+nq
                        aROXJV9hHw0khgZBehexoKp/oRDGeFZyOWaE/7oglgvzoubCK2Yu2m3+w4LuplOM
                        LucW3TCcGAb0n4IzP7yzaa/uTIynppc9G7Urh2CTMqW+Q+a4JhWQ0km5x/y7yumu
                        Yi2yvx3bsjZEvk+EFXJctU7WjVAWk0SLrG6zMyXji4sCAwEAAaOCAycwggMjMIGZ
                        BggrBgEFBQcBAQSBjDCBiTBIBggrBgEFBQcwAoY8aHR0cDovL3d3dy5jZXJ0aWZp
                        Y2Fkb2RpZ2l0YWwuY29tLmJyL2NhZGVpYXMvc2VyYXNhcmZidjIucDdiMD0GCCsG
                        AQUFBzABhjFodHRwOi8vb2NzcC5jZXJ0aWZpY2Fkb2RpZ2l0YWwuY29tLmJyL3Nl
                        cmFzYXJmYnYyMAkGA1UdEwQCMAAwHwYDVR0jBBgwFoAUsqDEPUaefMiFbAgeEDKU
                        ZUZwQXMwcQYDVR0gBGowaDBmBgZgTAECAQ0wXDBaBggrBgEFBQcCARZOaHR0cDov
                        L3B1YmxpY2FjYW8uY2VydGlmaWNhZG9kaWdpdGFsLmNvbS5ici9yZXBvc2l0b3Jp
                        by9kcGMvZGVjbGFyYWNhby1yZmIucGRmMIHzBgNVHR8EgeswgegwSqBIoEaGRGh0
                        dHA6Ly93d3cuY2VydGlmaWNhZG9kaWdpdGFsLmNvbS5ici9yZXBvc2l0b3Jpby9s
                        Y3Ivc2VyYXNhcmZidjIuY3JsMESgQqBAhj5odHRwOi8vbGNyLmNlcnRpZmljYWRv
                        cy5jb20uYnIvcmVwb3NpdG9yaW8vbGNyL3NlcmFzYXJmYnYyLmNybDBUoFKgUIZO
                        aHR0cDovL3JlcG9zaXRvcmlvLmljcGJyYXNpbC5nb3YuYnIvbGNyL1NlcmFzYS9y
                        ZXBvc2l0b3Jpby9sY3Ivc2VyYXNhcmZidjIuY3JsMA4GA1UdDwEB/wQEAwIF4DAd
                        BgNVHSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwQwgcAGA1UdEQSBuDCBtYEWV0VO
                        REVMTEBBTFBIQVRFQ1JOLkNPTaAtBgVgTAEDAqAkEyJST0JFUlRPIFdFTkRFTEwg
                        Uk9EUklHVUVTIERBIENPU1RBoBkGBWBMAQMDoBATDjAyOTAyNzM2MDAwMjYxoDgG
                        BWBMAQMEoC8TLTEyMDgxOTc1MDIwNTU1MjM0MDYwMDAwMDAwMDAwMDAwMDAwMDAw
                        MDAwMDAwMKAXBgVgTAEDB6AOEwwwMDAwMDAwMDAwMDAwDQYJKoZIhvcNAQELBQAD
                        ggIBAFpy2p4M7b8L8MT9AQ1OXIgo5DKyFRjT4fWtfwRxfQJiU1Q3mMr6QtaIUYCL
                        hltvjXP4DRcYMPcrpveI+ZMD7MbaFbbp6rI4AvpuSauvdCoraSm1w0sQ6NBwPVhT
                        WAak+o2V9L0u5i8WZe75oQgZ90kc1XAJqaS3djVOESvfAg9CDz4sQFzx3cMsHCvW
                        SfcDSmR0LrxLhTiN50FJjJgCnecxrpXa+jVds8GGjHly3DQUcWrTZG/+2AQt2H6J
                        9uwApWTxauVYNtqlF2lwdIZTTzSp6PkMNdVcUVGk2HGkPe+o92uQFI8VM4ZThcSy
                        /FZny95itLXowPZOW3Sa6MMZNBWZtct3q+V875pOqqX9qTy5l5dwR4UhtRklWRpy
                        MFLzAROc0NL0o+OLKWQT3P2dZEqWr8MhRRB7vjWAyvafRsQkgPZ+xpf/U9x49zm1
                        ERWzv6irTC8UjYAGq46goZMq8lBwcg2IIUryHR81cIVucrYyGKU1mXX6U9Xf8HdH
                        GDoO74ZGtTpGD65g0IEjGMCwXn902upNbm9RLpCT0FwQEV+Jgok2ME0xN2Fv+1is
                        DIfQSTU2S7ubS5si2IvtWoHP4+rWmT4W/Eg1gnvPQCyHZicYhGV9mMjqZDRPfhw5
                        YT8qWOEfIbNQoSN+Kxqqy4WMIXptvESgwXrsLjyukPxbiI+6
                    </ds:X509Certificate>
                </ds:X509Data>
            </ds:KeyInfo>
        </ds:Signature>`

valew e obrigado pelas dicas

**Comment by rodrigorodriguescosta** [comment]
Cara, assim que postei aqui, resolvi com um post antigo lá na lib Signxml, inclusive aberto por mim e vc também resolveu, é só fazer assim

`signer = xmldsig(your_xml_tree)
ns = {}
ns[None] = signer.namespaces['ds']
signer.namespaces = ns
signed = signer.sign(key=your_key,
                     cert=your_cert,
                     c14n_algorithm='http://www.w3.org/TR/2001/REC-xml-c14n-20010315',
                     reference_uri=your_reference_uri)
`

https://github.com/XML-Security/signxml/issues/30#issuecomment-149618525

**Comment by danimaribeiro** [comment]
Fixed https://github.com/danimaribeiro/PyTrustNFe/commit/482480fa08c2d2ba71837fa8a7b80835817fc72d
