### ISSUE TITLE
Validação do esquema de xml da NFe 

### ISSUE THREAD

**Issue by edsonitk** [danimaribeiro/PyTrustNFe#44]
Olá Danimar,

Qdo tiver um tempo, dá uma olhada na função de validação do xml. Eu fiz um teste colocando um cnpj inválido no destinatário e a rotina apontou falha em dados do emitente como cnpj, nro e na natureza de operação.

**Comment by danimaribeiro** [comment]
A função de validar pelo schema?

**Comment by edsonitk** [comment]
Isso mesmo.

**Comment by danimaribeiro** [comment]
Olhando o schema, ele valida apenas o tamanho do cnpj (14 digitos), fora isto não deveria lançar exceção.

Me manda uma imagem do erro.

**Comment by edsonitk** [comment]
É assim, eu mandei pro xml um cnpj válido ( no destinatário ), mas com traços e pontos de propósito para gerar erro. E a função valida_nfe() retorna erros em outros campos que estão com valores corretos.
