### ISSUE TITLE
Issue with Discriminacao, Discriminacao is not respect '\n'

### ISSUE THREAD

**Issue by devishree-git** [danimaribeiro/PyTrustNFe#63]
Hello,

from pytrustnfe.nfse.paulistana import envio_lote_rps
envio_lote_rps(certificado, nfse=nfse_values)
Note: nfse_values = Input Data

As From Odoo I passed Description/Discriminacao in multiple lines

Example:
-------------
https://photos.app.goo.gl/KKFaJFjEgodxucqj1

When Library Generate xml file,
<Discriminacao>SUPORTE T&#xC9;CNICO MENSAL - PORTAL DE FORNECEDORES   PEDIDO: 450018716 RESPONS&#xC1;VEL: PAULO SILVA REFEREN (1) Esta NFS-e foi emitida com respaldo na Lei n&#xBA; 14.097/2005; (2) Data do vencimento do ISS desta nota &#xE9; 10/03/2017</Discriminacao>

Example Result:
-----------------------
https://photos.app.goo.gl/jMZkQH3hByQ6W4e82

Expected Result sould be like:
-----------------------------------------
SUPORTE TÉCNICO MENSAL - PORTAL DE FORNECEDORES 

PEDIDO: 450018716
RESPONSÁVEL: PAULO SILVA
REFERENTE SUPORTE MES 05/2017

IRRF                  R$ 36,50
PIS                     R$ 15,82
COFINS             R$ 73,01
CSLL                  R$ 24,34

Waiting for suggestions.

Thank You,
Devishree

**Comment by danimaribeiro** [comment]
According to documentation chars 13 and 10 should be replaced by pipe |

**Comment by devishree-git** [comment]
Ok, I removed Normalization part which was with pipe | and after that It's working Fine for me.
Thank You.

**Comment by danimaribeiro** [comment]
Can you send the fix?

**Comment by yk2kus** [comment]
https://github.com/danimaribeiro/PyTrustNFe/pull/68
