### ISSUE TITLE
Dificuldades com o PyTrustNFe

### ISSUE THREAD

**Issue by erickod** [danimaribeiro/PyTrustNFe#64]
Estou utilizando o PyTrustNFe para carregar o certificado digital, extrair os dados que preciso dele.
No meu software consegui gerar o xml, porém não consegui realizar a assinatura do mesmo.

Sei que há o método assina_xml(self, xml_element, reference), mas não tenho certeza sobre o que colocar como parâmetro para "reference".

Outra coisa, as tags SignatureValue e X509Certificate são geradas pelo método acima ou preciso colocá-las separado no meu xml?

Pesquisei bastante, mas não tem muita informação sobre, por isso pergunto aqui.

**Comment by danimaribeiro** [comment]
Tem uns exemplos de uso:
https://github.com/danimaribeiro/PyTrustNFe#exemplos-de-uso-da-nfe
