### ISSUE TITLE
Erro Unicode strings with encoding declaration are not supported

### ISSUE THREAD

**Issue by crsilveira** [danimaribeiro/PyTrustNFe#85]
Ao gerar a NFe no odoo 11, tive o erro abaixo .

PyTrustNFe3-0.9.4-py3.5.egg/pytrustnfe/utils.py", line 89, in gerar_nfeproc
    docRecibo = ET.fromstring(recibo)
  File "src/lxml/etree.pyx", line 3230, in lxml.etree.fromstring (src/lxml/etree.c:81055)
  File "src/lxml/parser.pxi", line 1866, in lxml.etree._parseMemoryDocument (src/lxml/etree.c:121176)
ValueError: Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.

def gerar_nfeproc(envio, recibo):
    NSMAP = {None: 'http://www.portalfiscal.inf.br/nfe'}
    root = ET.Element("nfeProc", versao="3.10", nsmap=NSMAP)
    docEnvio = ET.fromstring(envio)
*    docRecibo = ET.fromstring(recibo)

Só consegui passar fazendo :  
*    docRecibo = ET.fromstring(recibo, encoding='unicode' )

**Comment by crsilveira** [comment]
ValueError: Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.

Resolvido definitivamente assim : 

def gerar_nfeproc(envio, recibo):
    NSMAP = {None: 'http://www.portalfiscal.inf.br/nfe'}
    root = ET.Element("nfeProc", versao="3.10", nsmap=NSMAP)
    docEnvio = ET.fromstring(envio)
    **recibo = recibo.replace('<?xml version="1.0" encoding="utf-8"?>', '')**
    docRecibo = ET.fromstring(recibo)

    nfe = _find_node(docEnvio, "NFe")
    protocolo = _find_node(docRecibo, "protNFe")
    if nfe is None or protocolo is None:
        return ''
    root.append(nfe)
    root.append(protocolo)
    return ET.tostring(root)

**Comment by danimaribeiro** [comment]
Corrigido.
