### ISSUE TITLE
XML Gerado está vindo sem o CNPJ

### ISSUE THREAD

**Issue by marielofeitosa** [danimaribeiro/PyTrustNFe#87]
Olá Danimar tudo bem?

Estou com um problema na hora de gerar a NFe em ambiente de testes, como pode observar pelo print abaixo o CNPJ de ambos, emitente e destinatário não está sendo gerado no XML. Isso tem causado erros de validação na validação dos schemas.

![print](https://user-images.githubusercontent.com/29415090/34871832-bd9f70de-f76d-11e7-97c0-d70c58166fe5.png)
![print1](https://user-images.githubusercontent.com/29415090/34871922-fdd216ac-f76d-11e7-8e7e-e7142e9500ae.png)

Poderia por favor me informar o que eu possa estar fazendo de errado?

Vi que no exemplo de código de geração no odoo Brasil é informado juntamente uma propriedade "tipo" no emitente e no destinatário. Saberia informar para qual finalidade ela é necessária?

No exemplo abaixo, está como estou enviando a tag "emit" para a geração do XML
![print2](https://user-images.githubusercontent.com/29415090/34872137-99b3f892-f76e-11e7-8f77-d88086e67b20.png)
 
Qualquer ajuda será apreciada, obrigado desde já

Atenciosamente,

**Comment by danimaribeiro** [comment]
Exatamente o parametro tipo que você deve especificar também:

https://github.com/danimaribeiro/PyTrustNFe/blob/master3/pytrustnfe/nfe/templates/NfeAutorizacao.xml#L77

**Comment by marielofeitosa** [comment]
Obrigado amigo, deu certinho, você já esta vendo a NFE4?

Atenciosamente,

**Comment by marielofeitosa** [comment]
Obrigado amigo,

Aproveitando o caso, saberia por favor me informar como utilizo o método de
consulta do Status do Serviço da NFe?

Tentei da seguinte forma:

dados = {
    'obj': {
        'ambiente': self.tipo_ambiente,
        'estado': self.emit['enderEmit']['cMun'][:2]
    },
}
return nfe_status_servico(
    self.certificate.certificado,
    **dados
)


A propriedade certificate da minha classe NFe, já faz o devido
armazenamento do certificado em questão em Base64. Passando os dados para
consulta recebo a seguinte exceção:

root = etree.fromstring(xml, parser=parser)
  File "src/lxml/lxml.etree.pyx", line 3228, in lxml.etree.fromstring
(src/lxml/lxml.etree.c:79609)
  File "src/lxml/parser.pxi", line 1843, in lxml.etree._parseMemoryDocument
(src/lxml/lxml.etree.c:119069)
ValueError: Unicode strings with encoding declaration are not supported.
Please use bytes input or XML fragments without declaration.

Obrigado desde já,

Atenciosamente


2018-01-12 12:08 GMT-03:00 Danimar Ribeiro <notifications@github.com>:

**Comment by marielofeitosa** [comment]
Olá,

Eu acabei de assinar o abaixo-assinado "#RenanNão - Não queremos Renan
Calheiros presidente do Senado" e queria saber se você pode ajudar
assinando também.

A nossa meta é conseguir 13.886 assinaturas e precisamos de mais apoio.
Você pode ler mais sobre este assunto e assinar o abaixo-assinado aqui:

http://chng.it/NDpXHJjHwv

Obrigado!
Mariel
