### ISSUE TITLE
Como desenvolver sem certificado A1 e A3

### ISSUE THREAD

**Issue by Rodrigocg** [danimaribeiro/PyTrustNFe#91]
Existe algum ambiente para desenvolvimento em que eu não precise de um certificado válido? 
Não tenho empresa para adquirir um....

Desde já agradeço.

**Comment by danimaribeiro** [comment]
Infelizmente não.

Em 19 de jan de 2018 2:08 AM, "Rodrigo de Carvalho Gomes" <
notifications@github.com> escreveu:

**Comment by Rodrigocg** [comment]
Obrigado pela informaçao.
