### ISSUE TITLE
493 - Rejeição: Evento não atende o Schema XML específico

### ISSUE THREAD

**Issue by crsilveira** [danimaribeiro/PyTrustNFe#92]
Ao gerar a carta de correção tenho o erro acima, a validação do XML está correta, alguma ideia de como posso resolver isso  ?

**Comment by danimaribeiro** [comment]
Teria que pegar o xml e validar ele no validador do RS.

**Comment by crsilveira** [comment]
Sim, fiz a validação lá., tudo certo:

Resultado da Validação do Schema e de Regras de Negócio:
Parser XML: Nenhum erro encontrado
Tipo de Mensagem: Lote de Registro de Evento
Schema XML: Nenhum erro encontrado
Evento Carta de Correção Eletrônica 
Assinatura Digital: Válida

**Comment by crsilveira** [comment]
segue o xml  :
<envEvento versao="1.00"><idLote>8</idLote><evento versao="1.00"><infEvento Id="ID1101103518018238277000011955001000010580133784701501"><cOrgao>35</cOrgao><tpAmb>2</tpAmb><CNPJ>82382770000119</CNPJ><chNFe>35180182382770000119550010000105801337847015</chNFe><dhEvento>2018-01-30T10:50:13-00:00</dhEvento><tpEvento>110110</tpEvento><nSeqEvento>1</nSeqEvento><verEvento>1.00</verEvento><detEvento versao="1.00"><descEvento>Carta de Correção</descEvento><xCorrecao>Teste corrigir a Descricao do Produto = PRODUTO X</xCorrecao><xCondUso>A Carta de Correção é disciplinada pelo § 1º-A do art. 7º do Convênio S/N, de 15 de dezembro de 1970 e pode ser utilizada para regularização de erro ocorrido na emissão de documento fiscal, desde que o erro não esteja relacionado com: I - as variáveis que determinam o valor do imposto tais como: base de cálculo, alíquota, diferença de preço, quantidade, valor da operação ou da prestação; II - a correção de dados cadastrais que implique mudança do remetente ou do destinatário; III - a data de emissão ou de saída.</xCondUso></detEvento></infEvento><Signature><SignedInfo><CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/><SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/><Reference URI="#ID1101103518018238277000011955001000010580133784701501"><Transforms><Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/><Transform Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/></Transforms><DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/><DigestValue>3Q3hfPGMTTstPjHyYhxAlxHFMAE=</DigestValue></Reference></SignedInfo><SignatureValue>iP3luwcAHciheN1NKygDDAO5UoSsVQongTpJ+LH13JrY+ItYVxLBgr+3Yxl7aR/NKPVCIxsAOgStW2pUfLkJVslo8TMpb6QVeu2F4qOksxI27Hx3O4J3uaoHfpahPfWPav0DkeH7HHkKz+gqOdeuCDUQylP8V/q8MHWbOZ4IqFSzKtBASmv52exixpekE6aS9b+VgulrbKU7Yr6Qr3knTujGk79sRtxQBtPk32oWAMUREutNE+SAOABIYK00rH0WrfTAmfV+KSrc/EoQvXjKFai7AJ90pGt5lumCEmrazk+XqMLBf1O+12ncR4+CblQcxb7veq2nzFni6Gg2vne5uA==</SignatureValue><KeyInfo><X509Data><X509Certificate>MIIH9zCCBd+gAwIBAgIIDmNz0ANdzBMwDQYJKoZIhvcNAQELBQAwdTELMAkGA1UE
BhMCQlIxEzARBgNVBAoTCklDUC1CcmFzaWwxNjA0BgNVBAsTLVNlY3JldGFyaWEg
ZGEgUmVjZWl0YSBGZWRlcmFsIGRvIEJyYXNpbCAtIFJGQjEZMBcGA1UEAxMQQUMg
U0VSQVNBIFJGQiB2MjAeFw0xNzA0MjYxMzU3MDBaFw0xODA0MjYxMzU3MDBaMIHk
MQswCQYDVQQGEwJCUjELMAkGA1UECBMCU1AxEzARBgNVBAcTCkpBR1VBUklVTkEx
EzARBgNVBAoTCklDUC1CcmFzaWwxNjA0BgNVBAsTLVNlY3JldGFyaWEgZGEgUmVj
ZWl0YSBGZWRlcmFsIGRvIEJyYXNpbCAtIFJGQjEWMBQGA1UECxMNUkZCIGUtQ05Q
SiBBMTESMBAGA1UECxMJQVIgU0VSQVNBMTowOAYDVQQDEzFHUkVFTiBIT1VTRSBF
U1RVRkFTIEFHUklDT0xBUyBMVERBOjY0OTk2NzcwMDAwMTE5MIIBIjANBgkqhkiG
9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvIau70T+PP3w87/E99Y3jGxXMp4o2DTAcmfi
y1QwqkIsfnE3EumJgyVY6SfnRs5b39iXnpz7SrLwJvU1k1hXdzhaMz5aFC+0yLGJ
E0EA5XxiKnjx7rqLmK9ji3TNeJr9TaFdpiXb1xNwWCMZVqdTh+aHS2VDj/Lcladm
Za+ygb7yZh2vv4rr2Yi65Mthoi5dYzD1DqT1ZUHKfq9D5fT/EWHJQdiAcpCVEOit
vJWmDya+XPQPCtsPdKpIZSTGuQqzsC10HAndxtY8O5XhDfOLi5h65iSjDRqc8nOs
7+t4Wd4FOJGdYKQ6hKrC58txR09SpMjNU/XhJt85JkdL48d7BQIDAQABo4IDGTCC
AxUwgZkGCCsGAQUFBwEBBIGMMIGJMEgGCCsGAQUFBzAChjxodHRwOi8vd3d3LmNl
cnRpZmljYWRvZGlnaXRhbC5jb20uYnIvY2FkZWlhcy9zZXJhc2FyZmJ2Mi5wN2Iw
PQYIKwYBBQUHMAGGMWh0dHA6Ly9vY3NwLmNlcnRpZmljYWRvZGlnaXRhbC5jb20u
YnIvc2VyYXNhcmZidjIwCQYDVR0TBAIwADAfBgNVHSMEGDAWgBSyoMQ9Rp58yIVs
CB4QMpRlRnBBczBxBgNVHSAEajBoMGYGBmBMAQIBDTBcMFoGCCsGAQUFBwIBFk5o
dHRwOi8vcHVibGljYWNhby5jZXJ0aWZpY2Fkb2RpZ2l0YWwuY29tLmJyL3JlcG9z
aXRvcmlvL2RwYy9kZWNsYXJhY2FvLXJmYi5wZGYwgfMGA1UdHwSB6zCB6DBKoEig
RoZEaHR0cDovL3d3dy5jZXJ0aWZpY2Fkb2RpZ2l0YWwuY29tLmJyL3JlcG9zaXRv
cmlvL2xjci9zZXJhc2FyZmJ2Mi5jcmwwRKBCoECGPmh0dHA6Ly9sY3IuY2VydGlm
aWNhZG9zLmNvbS5ici9yZXBvc2l0b3Jpby9sY3Ivc2VyYXNhcmZidjIuY3JsMFSg
UqBQhk5odHRwOi8vcmVwb3NpdG9yaW8uaWNwYnJhc2lsLmdvdi5ici9sY3IvU2Vy
YXNhL3JlcG9zaXRvcmlvL2xjci9zZXJhc2FyZmJ2Mi5jcmwwDgYDVR0PAQH/BAQD
AgXgMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDBDCBsgYDVR0RBIGqMIGn
gRdCUlVOQUBHUkVFTkhPVVNFLkNPTS5CUqAZBgVgTAEDAqAQEw5ERU5JUyBHQUxW
QU5JTqAZBgVgTAEDA6AQEw42NDk5Njc3MDAwMDExOaA9BgVgTAEDBKA0EzIwNjEy
MTk2NjA4NTcxOTY0ODA3MDAwMDAwMDAwMDAwMDAwMDAxMjkxNjQwNDVTU1BTUKAX
BgVgTAEDB6AOEwwwMDAwMDAwMDAwMDAwDQYJKoZIhvcNAQELBQADggIBAMV8Cj9c
kUgIUWg4c/DjHTN+Vl8mfrMtBREXWgS4yN4LrqOB9NnOgwjzKoXvh/VW2+Kp+tYZ
qejQJ+9aruMWXw3hjVl0PHjfipe8Za7IA9jepIjhKrMkscsXeq8PE47wXKfcffHB
pxGQ21kNVShprAWo+6JfhrDLPh6fFYGy5o9Dfs/72UTKPNz51uXb7EJ3pRp/F1jb
P/bBpOLjXrU+31xaOGjeumnysIJAFz1re2lfty0GzihNy5u0+s4hqY4vB5N+5+Rk
AcBnlVy40kiwYHjAXs7tkt0NzUYBxrbvLh7lCvuORrOYVQ34VKxhOOObLamMYcna
aVscwwFzrGpdfp3oRrKFreKzRk8QTDfySDEN0qXJQHTOX3bc8YhsLxJMD1Qy43M3
/xguY71gZvwxncg7jxGT/vB3ddeMJbbehCvbPV+AB4diBnelMpXLz7fdkGFUJ4YH
HpoTLttIKfmk6vsZ4FLEpVnxkTfSm2kveWcC8Iv+SMvP8ek38V1LH61FkHNaHMxO
Xp8rw1d7nsOiS8ddruNn+vCPOI4mWC0bZ6ReA1+NiLEAMphVnqffEHzI3Kkhv1xE
qdb0aVcKD4HVuhHmatmyd1VRQUgf3+UnCIAWWJVlP3oFDzCJS0LuroeBPvA15Qfm
g9YsMZSqOWZWW9yD5LSGfOh2Ue24CjJzWGiP
</X509Certificate></X509Data></KeyInfo></Signature></evento></envEvento>

O CNPJ ai não é real, mas no validado acima é . 
Obs.: ambiente Homologação fiz isso, mas no Produção está acontecendo a mesma coisa.

**Comment by crsilveira** [comment]
Danimar tem idéia do q eu possa fazer pra descobrir o por que do erro ?

**Comment by danimaribeiro** [comment]
Eu vi que temos esse erro aqui também.

**Comment by crsilveira** [comment]
Aqui tirando os acentos do Texto, que esta no template , para isso , dai a carta foi.:  
<descEvento>Carta de Correcao</descEvento>
xCondUso>A Carta de Correcao e disciplinada pelo paragrafo 1o-A do art. 7o do Convenio S/N, de 15 de dezembro de 1970 e pode ser utilizada para regularizacao de erro ocorrido na emissao de documento fiscal, desde que o erro nao esteja relacionado com: I - as variaveis que determinam o valor do imposto tais como: base de calculo, aliquota, diferenca de preco, quantidade, valor da operacao ou da prestacao; II - a correcao de dados cadastrais que implique mudanca do remetente ou do destinatario; III - a data de emissao ou de saida.</xCondUso>

**Comment by rodriguesraphael** [comment]
Também passei por este mesmo erro.
Resolvi adicionando o código:
`xml_enviar = xml_enviar.encode('utf-8')`
Depois desta linha:
https://github.com/danimaribeiro/PyTrustNFe/blob/6117a8b63fb3ccbd5ec10e283b3005a36b26f317/pytrustnfe/nfe/comunicacao.py#L29

**Comment by danimaribeiro** [comment]
Quais os estados que vocês estavam tendo esse problema?

Testei em alguns estados e funciona, porém no estado de MG nenhuma das duas soluções resolve.

**Comment by danimaribeiro** [comment]
Corrigido.
