### ISSUE TITLE
Error installing on ubuntu 16.04 python 3

### ISSUE THREAD

**Issue by falexandresilva** [danimaribeiro/PyTrustNFe#94]
I've tried in two systems and in both receive this error message.

Collecting https://github.com/danimaribeiro/PyTrustNFe/archive/master3.zip
  Downloading https://github.com/danimaribeiro/PyTrustNFe/archive/master3.zip
     | 235kB 461kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-f3_ua59z-build/setup.py", line 41, in <module>
        long_description=open('README.md', 'r').read(),
      File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 654: ordinal not in range(128)

**Comment by danimaribeiro** [comment]
Tente instalar via pip.

**Comment by falexandresilva** [comment]
Foi  a primeira tentativa. Dá o mesmo erro.

root@8e58024d118e:/# pip install https://github.com/danimaribeiro/PyTrustNFe/archive/master3.zip
Collecting https://github.com/danimaribeiro/PyTrustNFe/archive/master3.zip
  Downloading https://github.com/danimaribeiro/PyTrustNFe/archive/master3.zip
     | 235kB 967kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-nfaff75h-build/setup.py", line 41, in <module>
        long_description=open('README.md', 'r').read(),
      File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 654: ordinal not in range(128)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-nfaff75h-build/

**Comment by danimaribeiro** [comment]
Rode este comando:
python3 -c "import sys;print(sys.getdefaultencoding())"

Deve aparecer "utf-8"

**Comment by falexandresilva** [comment]
Apareceu o UTF-8.

root@8e58024d118e:/# python3 -c "import sys;print(sys.getdefaultencoding())"
utf-8

**Comment by Lamboy88** [comment]
mais um

pip3 install PyTrustNFe
Collecting PyTrustNFe
  Using cached PyTrustNFe-0.1.10.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-64seyl08/PyTrustNFe/setup.py", line 4, in <module>
        long_description = open('README.md').read()
    FileNotFoundError: [Errno 2] No such file or directory: 'README.md'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-64seyl08/PyTrustNFe/

**Comment by gmonnerat** [comment]
A ultima versão  não é compatível com python 3?

gabriel@localhost: $ pip install PyTrustNFe==0.1.49
Collecting PyTrustNFe==0.1.49
  Could not find a version that satisfies the requirement PyTrustNFe==0.1.49 (from versions: 0.1.8, 0.1.9, 0.1.10)
No matching distribution found for PyTrustNFe==0.1.49

gabriel@localhost:$ pip install PyTrustNFe
Collecting PyTrustNFe
  Using cached https://files.pythonhosted.org/packages/1f/a6/4f75fee5d8e64e808b7511d63528dda5376da8d5c93f7b28597ed835a1f8/PyTrustNFe-0.1.10.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-wet1spps/PyTrustNFe/setup.py", line 4, in <module>
        long_description = open('README.md').read()
    FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-wet1spps/PyTrustNFe/

gabriel@localhost:$ python --version
Python 3.6.4

**Comment by danimaribeiro** [comment]
https://pypi.org/project/PyTrustNFe3/

**Comment by diegocatalao** [comment]
Esse problema de build eu resolvi usando VirtualEnv.
mkvirtualenv whatever
pip install PyTrustNFe3
